### ISSUE TITLE
`pulp test` fails on CI

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-spec/purescript-spec#129]
What's the point of this anyway? Can I delete it?

**Comment by fsoikin** [comment]
I think this might be fixed by https://github.com/purescript-spec/purescript-spec/pull/130

As for the point, my guess is that it's testing that the library would compile and run normally under both Spago and Pulp, so as to support downstream projects based on either. When Pulp finally goes away for good, I think it can be removed, but for now, I don't see any harm in keeping it.
