### ISSUE TITLE
Add something like setUp and tearDown

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript-spec/purescript-spec#43]
Add something like setUp and tearDown, something like hooks in hspec:
https://hspec.github.io/writing-specs.html

**Comment by mostalive** [comment]
I've been working around this by creating items that require side effects inn main, and passing them in, but that is not very sustainable - it goes messy quite quickly.

**Comment by owickstrom** [comment]
@mostalive I see. I'll try to find some time and implement the design discussed in #44. Would that be nicer for your usage?

**Comment by mostalive** [comment]
I think it would, although the fact that I have that much state is also saying something about my tests...

**Comment by owickstrom** [comment]
Yeah, perhaps. Do you have any example that you can share?

**Comment by mostalive** [comment]
(beforeEach is almost done now, and I am finally getting around to updating this, so this is more or less a note to self ;-)),
Example:

https://github.com/mostalive/purescript-firebase/blob/master/test/WriteGenericSpec.purs

```
 location <- entriesRef
```
is duplicated in multipe it's the last one isnt' so that smells of a separate describe block.
