### ISSUE TITLE
Let Assertions Return Either

### ISSUE THREAD

**Issue by adius** [purescript-spec/purescript-spec#68]
I think a structure like this would provide a much better separation of concerns:

```purescript
shouldEqual :: String -> String -> Either String String
shouldEqual actual expected =
  if (actual /= expected)
  then Left "\"" <> actual <> "\" /= \"" <> expected <> "\""
  else Right ""


shouldBeOk :: forall r. Either String String -> Aff r Unit
shouldBeOk value = case value of
  Left error -> fail error
  Right _ -> (pure unit)


it "should do something" do
  shouldBeOk do
    actual <- getSomeEither
    expected <- getAnotherEither
    actual `shouldEqual` expected
```

Then all assertions would simply be of type `String -> String -> Either String String`

**Comment by adius** [comment]
Now that I think of it, is the current signature necessary to run it async? 🤔

**Comment by safareli** [comment]
@adius would be great if you can take a look at #82 because there i'm adding:
`hoistSpec :: (m ~> g) -> Spec' m ~> Spec' g` 

It means you can use something other then `Aff Unit` for `it` blocks, so if you have use `Either String Unit`, then you can do `hoistSpec (either throw pure)` which will throw for all `Left` values.

**Comment by owickstrom** [comment]
@safareli correct me if I'm wrong, but this means if one wants to run an `Either`-based spec for only a subset of a test suite, you could `hoistSpec` that suite into a larger `Aff Unit`-based suite.
